CREATE TABLE IF NOT EXISTS ga_generated_fixes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    evaluation_id INT NOT NULL,
    project_id INT NOT NULL,
    user_id INT NOT NULL,
    fix_type ENUM('rewrite_ads', 'add_negatives', 'remove_duplicates', 'add_extensions') NOT NULL,
    scope_level ENUM('campaign', 'ad_group') NOT NULL,
    campaign_name VARCHAR(255) DEFAULT NULL,
    ad_group_name VARCHAR(255) DEFAULT NULL,
    ad_group_id_google VARCHAR(50) DEFAULT NULL,
    campaign_id_google VARCHAR(50) DEFAULT NULL,
    issue_description TEXT DEFAULT NULL,
    recommendation TEXT DEFAULT NULL,
    ai_response JSON DEFAULT NULL,
    display_text TEXT DEFAULT NULL,
    status ENUM('generated', 'applied', 'failed') NOT NULL DEFAULT 'generated',
    applied_at DATETIME DEFAULT NULL,
    apply_result JSON DEFAULT NULL,
    credits_used DECIMAL(10,2) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_evaluation (evaluation_id),
    INDEX idx_project (project_id),
    INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
